# 10 Minutes to Pandas

> Link : https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html

----

In [1]:
import pandas as pd
import numpy as np

## Object Creation

In [2]:
s = pd.Series([2, 3, 5, np.nan, 0])
s

0    2.0
1    3.0
2    5.0
3    NaN
4    0.0
dtype: float64

In [3]:
dates = pd.date_range('2020-01-01', periods = 6)
dates

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06'],
              dtype='datetime64[ns]', freq='D')

In [4]:
df = pd.DataFrame(np.random.randint(0,10,size=(6,4)), index=dates, columns = list('ABCD'))
df

A  B  C  D
2020-01-01  7  2  3  5
2020-01-02  8  2  0  9
2020-01-03  0  3  8  7
2020-01-04  3  2  5  0
2020-01-05  6  4  1  9
2020-01-06  3  3  7  0

 DataFrame by passing a dict of objects that can be converted to series-like.

In [5]:
np.array(list(range(0,4)))

array([0, 1, 2, 3])

In [6]:
np.random.randint(0,100,size=(4,1))

array([[63],
       [96],
       [63],
       [66]])

In [7]:
np.array([3] * 4, dtype='int32')

array([3, 3, 3, 3])

In [8]:
np.array(np.random.randint(0,100,4))

array([59, 68, 89, 84])

In [9]:
df2 = pd.DataFrame({
    'A': 1,
    'B': np.array(np.random.randint(0,100,size=(4))),
    'C': pd.Series([1,2,56,87], dtype='float32'),
    'D': np.array(list(range(0,4)))
#     'D': np.array([3] * 4, dtype = 'int32')
#          np.array([3] * 4, dtype='int32')
},
index=list(range(0,4)))

df2

A   B     C  D
0  1  74   1.0  0
1  1  84   2.0  1
2  1  94  56.0  2
3  1  44  87.0  3

In [10]:
df2 = pd.DataFrame({'A': 1.,
   ...:                     'B': pd.Timestamp('20130102'),
   ...:                     'C': pd.Series(1, index=list(range(4)), dtype='float32'),
   ...:                     'D': np.array([3] * 4, dtype='int32'),
   ...:                     'E': pd.Categorical(["test", "train", "test", "train"]),
   ...:                     'F': 'foo'})

In [11]:
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

In [22]:
df = pd.read_csv("Loan_Prediction.csv", index_col = "Loan_ID")
df.head()

Gender Married Dependents     Education Self_Employed  \
Loan_ID                                                          
LP001002   Male      No          0      Graduate            No   
LP001003   Male     Yes          1      Graduate            No   
LP001005   Male     Yes          0      Graduate           Yes   
LP001006   Male     Yes          0  Not Graduate            No   
LP001008   Male      No          0      Graduate            No   

          ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
Loan_ID                                                                      
LP001002             5849                0.0         NaN             360.0   
LP001003             4583             1508.0       128.0             360.0   
LP001005             3000                0.0        66.0             360.0   
LP001006             2583             2358.0       120.0             360.0   
LP001008             6000                0.0       141.0             360.0   

          Credit_History Property_Area Loan_Status  
Loan_ID                                             
LP001002             1.0         Urban           Y  
LP001003             1.0         Rural           N  
LP001005             1.0         Urban           Y  
LP001006             1.0         Urban           Y  
LP001008             1.0         Urban           Y

## Viewing data