# 10 Minutes to Pandas

> Link : https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html

----

In [1]:
import pandas as pd
import numpy as np

## Object Creation

In [7]:
s = pd.Series([2, 3, 5, np.nan, 0])
s

0    2.0
1    3.0
2    5.0
3    NaN
4    0.0
dtype: float64

In [15]:
dates = pd.date_range('2020-01-01', periods = 6)
dates

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06'],
              dtype='datetime64[ns]', freq='D')

In [29]:
df = pd.DataFrame(np.random.randint(0,10,size=(6,4)), index=dates, columns = list('ABCD'))
df

A  B  C  D
2020-01-01  1  3  3  3
2020-01-02  5  7  1  9
2020-01-03  7  3  2  6
2020-01-04  1  3  5  4
2020-01-05  4  5  1  0
2020-01-06  9  4  0  6

 DataFrame by passing a dict of objects that can be converted to series-like.

In [39]:
np.array(list(range(0,4)))

array([0, 1, 2, 3])

In [37]:
np.random.randint(0,100,size=(4,1))

array([[79],
       [ 2],
       [56],
       [99]])

In [38]:
np.array([3] * 4, dtype='int32')

array([3, 3, 3, 3])

In [49]:
np.array(np.random.randint(0,100,4))

array([36, 17,  6, 11])

In [56]:
df2 = pd.DataFrame({
    'A': 1,
    'B': np.array(np.random.randint(0,100,size=(4))),
    'C': pd.Series([1,2,56,87], dtype='float32'),
    'D': np.array(list(range(0,4)))
#     'D': np.array([3] * 4, dtype = 'int32')
#          np.array([3] * 4, dtype='int32')
},
index=list(range(0,4)))

df2

A   B     C  D
0  1  75   1.0  0
1  1  94   2.0  1
2  1  51  56.0  2
3  1  11  87.0  3

In [ ]:
df2 = pd.DataFrame({'A': 1.,
   ...:                     'B': pd.Timestamp('20130102'),
   ...:                     'C': pd.Series(1, index=list(range(4)), dtype='float32'),
   ...:                     'D': np.array([3] * 4, dtype='int32'),
   ...:                     'E': pd.Categorical(["test", "train", "test", "train"]),
   ...:                     'F': 'foo'})